apiVersion: v1
kind: Service
metadata:
  name: lingua-exchange-svc
  namespace: lingua-exchange
spec:
  selector:
    app: lingua-exchange
  type: ClusterIP
  ports:
    - name: lingua-exchange-svc-http-port
      port: 8080
      targetPort: 8080

