-- 用户表 (users)
CREATE TABLE users
(
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    email                VARCHAR(255) UNIQUE,
    username             VARCHAR(100) NOT NULL,
    password_hash        VARCHAR(255),
    profile_picture      VARCHAR(255),
    native_language_id   BIGINT,
    learning_language_id BIGINT,
    language_level       VARCHAR(50),
    age                  INT,
    gender               ENUM ('male', 'female', 'other'),
    interests            TEXT,
    country_id           BIGINT,
    registration_date    TIMESTAMP                             DEFAULT CURRENT_TIMESTAMP,
    last_login           TIMESTAMP,
    status               ENUM ('active', 'inactive', 'banned') DEFAULT 'active',
    email_verified       BOOLEAN                               DEFAULT FALSE,
    verification_token   VARCHAR(255),
    token_expiration     TIMESTAMP,
    created_at           datetime     null,
    updated_at           datetime     null,
    deleted_at           datetime     null,
    FOREIGN KEY (native_language_id) REFERENCES languages (id) ON DELETE SET NULL,
    FOREIGN KEY (learning_language_id) REFERENCES languages (id) ON DELETE SET NULL,
    FOREIGN KEY (country_id) REFERENCES countries (id) ON DELETE SET NULL
);

-- 群组聊天表 (group_chats)
CREATE TABLE group_chats
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    group_name VARCHAR(255) NOT NULL,
    created_by BIGINT       NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE
);

-- 群组成员表 (group_members)
CREATE TABLE group_members
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    group_id  BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_admin  BOOLEAN   DEFAULT FALSE,
    FOREIGN KEY (group_id) REFERENCES group_chats (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 群组消息表 (group_messages)
CREATE TABLE group_messages
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    group_id     BIGINT                                   NOT NULL,
    sender_id    BIGINT                                   NOT NULL,
    message      TEXT                                     NOT NULL,
    message_type ENUM ('text', 'image', 'audio', 'video') NOT NULL,
    timestamp    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES group_chats (id) ON DELETE CASCADE,
    FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 邮箱验证表 (email_verifications)
CREATE TABLE email_verifications
(
    id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    verification_token VARCHAR(255),
    token_expiration   TIMESTAMP,
    is_verified        BOOLEAN   DEFAULT FALSE,
    sent_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 语言表 (languages)
CREATE TABLE languages
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100)       NOT NULL,
    native_name VARCHAR(100)       NOT NULL,
    iso_code    VARCHAR(10) UNIQUE NOT NULL,
    created_at  datetime           null,
    updated_at  datetime           null,
    deleted_at  datetime           null
);

-- 国家表 (countries)
CREATE TABLE countries
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100)       NOT NULL,
    iso_code   VARCHAR(10) UNIQUE NOT NULL,
    created_at datetime           null,
    updated_at datetime           null,
    deleted_at datetime           null
);

-- 国家语言关联表 (country_languages)
CREATE TABLE country_languages
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    country_id  BIGINT   NOT NULL,
    language_id BIGINT   NOT NULL,
    created_at  datetime null,
    updated_at  datetime null,
    deleted_at  datetime null,
    FOREIGN KEY (country_id) REFERENCES countries (id) ON DELETE CASCADE,
    FOREIGN KEY (language_id) REFERENCES languages (id) ON DELETE CASCADE
);

-- 消息表 (messages)
CREATE TABLE messages
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    sender_id    BIGINT                                   NOT NULL,
    receiver_id  BIGINT                                   NOT NULL,
    message      TEXT                                     NOT NULL,
    message_type ENUM ('text', 'image', 'audio', 'video') NOT NULL,
    timestamp    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_delivered BOOLEAN   DEFAULT FALSE,
    is_read      BOOLEAN   DEFAULT FALSE,
    INDEX (sender_id),
    INDEX (receiver_id),
    INDEX (timestamp),
    FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 用户聊天记录备份表 (user_chat_backup)
CREATE TABLE user_chat_backup
(
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id         BIGINT                                   NOT NULL,
    chat_partner_id BIGINT                                   NOT NULL,
    message         TEXT                                     NOT NULL,
    message_type    ENUM ('text', 'image', 'audio', 'video') NOT NULL,
    timestamp       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_restored     BOOLEAN   DEFAULT FALSE,
    INDEX (user_id),
    INDEX (chat_partner_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (chat_partner_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 词汇表和笔记 (vocabulary_notes)
CREATE TABLE vocabulary_notes
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    word        VARCHAR(255) NOT NULL,
    note        TEXT,
    language_id BIGINT       NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (language_id) REFERENCES languages (id) ON DELETE CASCADE
);

-- 语音房间表 (voice_chat_rooms)
CREATE TABLE voice_chat_rooms
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    room_name   VARCHAR(255) NOT NULL,
    language_id BIGINT       NOT NULL,
    created_by  BIGINT       NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (language_id) REFERENCES languages (id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE
);

-- 第三方登录表 (third_party_auth)
CREATE TABLE third_party_auth
(
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    provider         VARCHAR(50)  NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    created_at       datetime     null,
    updated_at       datetime     null,
    deleted_at       datetime     null,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 虚拟货币系统表 (virtual_currency)
CREATE TABLE virtual_currency
(
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    balance             INT       DEFAULT 0,
    last_transaction_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 消息队列表 (message_queue)
CREATE TABLE message_queue
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    sender_id    BIGINT                                   NOT NULL,
    receiver_id  BIGINT                                   NOT NULL,
    message      TEXT                                     NOT NULL,
    message_type ENUM ('text', 'image', 'audio', 'video') NOT NULL,
    timestamp    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_sent      BOOLEAN   DEFAULT FALSE,
    retry_count  INT       DEFAULT 0,
    INDEX (receiver_id),
    FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 推送通知日志表 (push_notification_log)
CREATE TABLE push_notification_log
(
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id           BIGINT                                       NOT NULL,
    notification_type ENUM ('message', 'friend_request', 'system') NOT NULL,
    content           TEXT                                         NOT NULL,
    timestamp         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_clicked        BOOLEAN   DEFAULT FALSE,
    INDEX (user_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 用户设备表 (user_devices)
CREATE TABLE user_devices
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id      BIGINT                         NOT NULL,
    device_token VARCHAR(255)                   NOT NULL UNIQUE,
    device_type  ENUM ('iOS', 'Android', 'Web') NOT NULL,
    ip_address   VARCHAR(255)                   NOT NULL,
    created_at   datetime                       null,
    updated_at   datetime                       null,
    deleted_at   datetime                       null,
    last_active  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX (user_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 预插入数据 (languages, countries, country_languages)
INSERT INTO languages (id, native_name, name, visit_name, iso_code)
VALUES (1,
        'العربية',
        'Arabic (Israel)',
        '阿拉伯语（以色列)',
        'ar_IL'),
       (2, 'العربية', 'Arabic (Egypt)', '阿拉伯语（埃及)', 'ar_EG'),
       (3, '中文', 'Chinese Simplified', '中文简体', 'zh_CN'),
       (4, '中文', 'Chinese Tradition', '中文繁体', 'zh_TW'),
       (5, '粤语', 'Cantonese', '中文（香港)', 'zh_HK'),
       (6,
        'Nederlands',
        'Dutch (Netherlands)',
        '荷兰语',
        'nl_NL'),
       (7,
        'Nederlands',
        'Dutch (Belgium)',
        '荷兰语（比利时)',
        'nl_BE'),
       (8,
        'English',
        'English (United States)',
        '英语（美国)',
        'en_US'),
       (9,
        'English',
        'English (Australia)',
        '英语（澳大利亚)',
        'en_AU'),
       (10,
        'English',
        'English (Canada)',
        '英语（加拿大)',
        'en_CA'),
       (11, 'English', 'English (India)', '英语（印度)', 'en_IN'),
       (12,
        'English',
        'English (Ireland)',
        '英语（爱尔兰)',
        'en_IE'),
       (13,
        'English',
        'English (New Zealand)',
        '英语（新西兰)',
        'en_NZ'),
       (14,
        'English',
        'English (Singapore)',
        '英语（新加坡)',
        'en_SG'),
       (15,
        'English',
        'English (South Africa)',
        '英语（南非)',
        'en_ZA'),
       (16,
        'English',
        'English (United Kingdom)',
        '英语（英国)',
        'en_GB'),
       (17, 'Français', 'French', '法语', 'fr_FR'),
       (18,
        'Français',
        'French (Belgium)',
        '法语（比利时)',
        'fr_BE'),
       (19,
        'Français',
        'French (Canada)',
        '法语（加拿大)',
        'fr_CA'),
       (20,
        'Français',
        'French (Switzerland)',
        '法语（瑞士)',
        'fr_CH'),
       (21, 'Deutsch', 'German', '德语', 'de_DE'),
       (22,
        'Deutsch',
        'German (Liechtenstein)',
        '德语（列支敦斯登)',
        'de_LI'),
       (23,
        'Deutsch',
        'German (Austria)',
        '德语（奥地利)',
        'de_AT'),
       (24,
        'Deutsch',
        'German (Switzerland)',
        '德语（瑞士)',
        'de_CH'),
       (25, 'Italiano', 'Italian', '意大利语', 'it_IT'),
       (26,
        'Italiano',
        'Italian (Switzerland)',
        '意大利语（瑞士)',
        'it_CH'),
       (27,
        'Protuguês',
        'Portuguese (Brazil)',
        '葡萄牙语（巴西）',
        'pt_BR'),
       (28, 'Protuguês', 'Portuguese', '葡萄牙语', 'pt_PT'),
       (29, 'Español', 'Spanish', '西班牙语', 'es_ES'),
       (30,
        'Español',
        'Spanish (United States)',
        '西班牙语（美国)',
        'es_US'),
       (31, 'বাংলা', 'Bengali', '孟加拉语', 'bn_BD'),
       (32, 'বাংলা', 'Bengali (India)', '孟加拉语（印度)', 'bn_IN'),
       (33, 'hrvatski', 'Croatian', '克罗地亚语', 'hr_HR'),
       (34, 'čeština', 'Czech', '捷克语', 'cs_CZ'),
       (35, 'Dansk', 'Danish', '丹麦语', 'da_DK'),
       (36, 'ελληνικά', 'Greek', '希腊语', 'el_GR'),
       (37, 'עברית', 'Hebrew (Israel)', '希伯来语（以色列)', 'he_IL'),
       (38, 'עברית', 'Hebrew (Israel)', '希伯来语（以色列)', 'iw_IL'),
       (39, 'हिंदी', 'Hindi', '印度语', 'hi_IN'),
       (40, 'Magyar', 'Hungarian', '匈牙利语', 'hu_HU'),
       (41, '', 'Indonesian', '印度尼西亚语', 'in_ID'),
       (42, '日本語', 'Japanese', '日语', 'ja_JP'),
       (43, '한국어', 'Korean', '韩语', 'ko_KR'),
       (44, 'latviešu', 'Latvian', '拉脱维亚语', 'lv_LV'),
       (45, 'lietuvių', 'Lithuanian', '立陶宛语', 'lt_LT'),
       (46, 'polski', 'Polish', '波兰语', 'pl_PL'),
       (47, 'limba română', 'Romanian', '罗马尼亚语', 'ro_RO'),
       (48, 'српски', 'Serbian', '塞尔维亚语', 'sr_RS'),
       (49, 'slovenčina', 'Slovak', '斯洛伐克语', 'sk_SK'),
       (50, 'slovenščina', 'Slovenian', '斯洛文尼亚语', 'sl_SI'),
       (51, 'svenska', 'Swedish', '瑞典语', 'sv_SE'),
       (52, 'Filipino', 'Tagalog', '菲律宾语', 'tl_PH'),
       (53, 'Türkçe', 'Turkish', '土耳其语', 'tr_TR'),
       (54, 'українська', 'Ukrainian', '乌克兰语', 'uk_UA'),
       (55, 'Tiếng Việt', 'Vietnamese', '越南语', 'vi_VN');


INSERT INTO countries (id, iso_code, visit_name, name, phone_code)
VALUES (1, 'AD', '安道尔共和国', 'Andorra', 376),
       (2, 'AE', '阿拉伯联合酋长国', 'United Arab Emirates', 971),
       (3, 'AF', '阿富汗', 'Afghanistan', 93),
       (4, 'AG', '安提瓜和巴布达', 'Antigua and Barbuda', 1268),
       (5, 'AI', '安圭拉岛', 'Anguilla', 1264),
       (6, 'AL', '阿尔巴尼亚', 'Albania', 355),
       (7, 'AM', '亚美尼亚', 'Armenia', 374),
       (8, 'ASC', '阿森松', 'Ascension', 247),
       (9, 'AO', '安哥拉', 'Angola', 244),
       (10, 'AR', '阿根廷', 'Argentina', 54),
       (11, 'AT', '奥地利', 'Austria', 43),
       (12, 'AU', '澳大利亚', 'Australia', 61),
       (13, 'AZ', '阿塞拜疆', 'Azerbaijan', 994),
       (14, 'BB', '巴巴多斯', 'Barbados', 1246),
       (15, 'BD', '孟加拉国', 'Bangladesh', 880),
       (16, 'BE', '比利时', 'Belgium', 32),
       (17, 'BF', '布基纳法索', 'Burkina-faso', 226),
       (18, 'BG', '保加利亚', 'Bulgaria', 359),
       (19, 'BH', '巴林', 'Bahrain', 973),
       (20, 'BI', '布隆迪', 'Burundi', 257),
       (21, 'BJ', '贝宁', 'Benin', 229),
       (22, 'BL', '巴勒斯坦', 'Palestine', 970),
       (23, 'BM', '百慕大群岛', 'Bermuda Is.', 1441),
       (24, 'BN', '文莱', 'Brunei', 673),
       (25, 'BO', '玻利维亚', 'Bolivia', 591),
       (26, 'BR', '巴西', 'Brazil', 55),
       (27, 'BS', '巴哈马', 'Bahamas', 1242),
       (28, 'BW', '博茨瓦纳', 'Botswana', 267),
       (29, 'BY', '白俄罗斯', 'Belarus', 375),
       (30, 'BZ', '伯利兹', 'Belize', 501),
       (31, 'CA', '加拿大', 'Canada', 1),
       (32, 'KY', '开曼群岛', 'Cayman Is.', 1345),
       (33, 'CF', '中非共和国', 'Central African Republic', 236),
       (34, 'CG', '刚果', 'Congo', 242),
       (35, 'CH', '瑞士', 'Switzerland', 41),
       (36, 'CK', '库克群岛', 'Cook Is.', 682),
       (37, 'CL', '智利', 'Chile', 56),
       (38, 'CM', '喀麦隆', 'Cameroon', 237),
       (39, 'CN', '中国', 'China', 86),
       (40, 'CO', '哥伦比亚', 'Colombia', 57),
       (41, 'CR', '哥斯达黎加', 'Costa Rica', 506),
       (42, 'CS', '捷克', 'Czech', 420),
       (43, 'CU', '古巴', 'Cuba', 53),
       (44, 'CY', '塞浦路斯', 'Cyprus', 357),
       (45, 'CZ', '捷克', 'Czech Republic', 420),
       (46, 'DE', '德国', 'Germany', 49),
       (47, 'DJ', '吉布提', 'Djibouti', 253),
       (48, 'DK', '丹麦', 'Denmark', 45),
       (49, 'DO', '多米尼加共和国', 'Dominican Republic', 1809),
       (50, 'DZ', '阿尔及利亚', 'Algeria', 213),
       (51, 'EC', '厄瓜多尔', 'Ecuador', 593),
       (52, 'EE', '爱沙尼亚', 'Estonia', 372),
       (53, 'EG', '埃及', 'Egypt', 20),
       (54, 'ES', '西班牙', 'Spain', 34),
       (55, 'ET', '埃塞俄比亚', 'Ethiopia', 251),
       (56, 'FI', '芬兰', 'Finland', 358),
       (57, 'FJ', '斐济', 'Fiji', 679),
       (58, 'FR', '法国', 'France', 33),
       (59, 'GA', '加蓬', 'Gabon', 241),
       (60, 'GB', '英国', 'United Kingdom', 44),
       (61, 'GD', '格林纳达', 'Grenada', 1473),
       (62, 'GE', '格鲁吉亚', 'Georgia', 995),
       (63, 'GH', '加纳', 'Ghana', 233),
       (64, 'GM', '冈比亚', 'Gambia', 220),
       (65, 'GN', '几内亚', 'Guinea', 224),
       (66, 'GR', '希腊', 'Greece', 30),
       (67, 'GT', '危地马拉', 'Guatemala', 502),
       (68, 'GY', '圭亚那', 'Guyana', 592),
       (69, 'HK', '中国香港', 'Hong Kong', 852),
       (70, 'HN', '洪都拉斯', 'Honduras', 504),
       (71, 'HT', '海地', 'Haiti', 509),
       (72, 'HU', '匈牙利', 'Hungary', 36),
       (73, 'ID', '印度尼西亚', 'Indonesia', 62),
       (74, 'IE', '爱尔兰', 'Ireland', 353),
       (75, 'IL', '以色列', 'Israel', 972),
       (76, 'IN', '印度', 'India', 91),
       (77, 'IQ', '伊拉克', 'Iraq', 964),
       (78, 'IR', '伊朗', 'Iran', 98),
       (79, 'IS', '冰岛', 'Iceland', 354),
       (80, 'IT', '意大利', 'Italy', 39),
       (81, 'JM', '牙买加', 'Jamaica', 1876),
       (82, 'JO', '约旦', 'Jordan', 962),
       (83, 'JP', '日本', 'Japan', 81),
       (84, 'KE', '肯尼亚', 'Kenya', 254),
       (85, 'KG', '吉尔吉斯坦', 'Kyrgyzstan', 996),
       (86, 'KH', '柬埔寨', 'Cambodia', 855),
       (87, 'KI', '基里巴斯', 'Kiribati', 686),
       (88, 'KM', '科摩罗', 'Comoros', 269),
       (89, 'KP', '朝鲜', 'North Korea', 850),
       (90, 'KR', '韩国', 'South Korea', 82),
       (91, 'KW', '科威特', 'Kuwait', 965),
       (92, 'KZ', '哈萨克斯坦', 'Kazakhstan', 7),
       (93, 'LA', '老挝', 'Laos', 856),
       (94, 'LB', '黎巴嫩', 'Lebanon', 961),
       (95, 'LC', '圣卢西亚', 'Saint Lucia', 1758),
       (96, 'LI', '列支敦士登', 'Liechtenstein', 423),
       (97, 'LK', '斯里兰卡', 'Sri Lanka', 94),
       (98, 'LR', '利比里亚', 'Liberia', 231),
       (99, 'LS', '莱索托', 'Lesotho', 266),
       (100, 'LT', '立陶宛', 'Lithuania', 370),
       (101, 'LU', '卢森堡', 'Luxembourg', 352),
       (102, 'LV', '拉脱维亚', 'Latvia', 371),
       (103, 'LY', '利比亚', 'Libya', 218),
       (104, 'MA', '摩洛哥', 'Morocco', 212),
       (105, 'MC', '摩纳哥', 'Monaco', 377),
       (106, 'MD', '摩尔多瓦', 'Moldova', 373),
       (107, 'ME', '黑山', 'Montenegro', 382),
       (108, 'MG', '马达加斯加', 'Madagascar', 261),
       (109, 'MH', '马绍尔群岛', 'Marshall Islands', 692),
       (110, 'MK', '北马其顿', 'North Macedonia', 389),
       (111, 'ML', '马里', 'Mali', 223),
       (112, 'MM', '缅甸', 'Myanmar', 95),
       (113, 'MN', '蒙古', 'Mongolia', 976),
       (114, 'MO', '中国澳门', 'Macau', 853),
       (115, 'MR', '毛里塔尼亚', 'Mauritania', 222),
       (116, 'MT', '马耳他', 'Malta', 356),
       (117, 'MU', '毛里求斯', 'Mauritius', 230),
       (118, 'MV', '马尔代夫', 'Maldives', 960),
       (119, 'MW', '马拉维', 'Malawi', 265),
       (120, 'MX', '墨西哥', 'Mexico', 52),
       (121, 'MY', '马来西亚', 'Malaysia', 60),
       (122, 'MZ', '莫桑比克', 'Mozambique', 258),
       (123, 'NA', '纳米比亚', 'Namibia', 264),
       (124, 'NE', '尼日尔', 'Niger', 227),
       (125, 'NG', '尼日利亚', 'Nigeria', 234),
       (126, 'NI', '尼加拉瓜', 'Nicaragua', 505),
       (127, 'NL', '荷兰', 'Netherlands', 31),
       (128, 'NO', '挪威', 'Norway', 47),
       (129, 'NP', '尼泊尔', 'Nepal', 977),
       (130, 'NR', '瑙鲁', 'Nauru', 674),
       (131, 'NZ', '新西兰', 'New Zealand', 64),
       (132, 'OM', '阿曼', 'Oman', 968),
       (133, 'PA', '巴拿马', 'Panama', 507),
       (134, 'PE', '秘鲁', 'Peru', 51),
       (135, 'PG', '巴布亚新几内亚', 'Papua New Guinea', 675),
       (136, 'PH', '菲律宾', 'Philippines', 63),
       (137, 'PK', '巴基斯坦', 'Pakistan', 92),
       (138, 'PL', '波兰', 'Poland', 48),
       (139, 'PT', '葡萄牙', 'Portugal', 351),
       (140, 'PW', '帕劳', 'Palau', 680),
       (141, 'PY', '巴拉圭', 'Paraguay', 595),
       (142, 'QA', '卡塔尔', 'Qatar', 974),
       (143, 'RO', '罗马尼亚', 'Romania', 40),
       (144, 'RS', '塞尔维亚', 'Serbia', 381),
       (145, 'RU', '俄罗斯', 'Russia', 7),
       (146, 'RW', '卢旺达', 'Rwanda', 250),
       (147, 'SA', '沙特阿拉伯', 'Saudi Arabia', 966),
       (148, 'SB', '所罗门群岛', 'Solomon Islands', 677),
       (149, 'SC', '塞舌尔', 'Seychelles', 248),
       (150, 'SD', '苏丹', 'Sudan', 249),
       (151, 'SE', '瑞典', 'Sweden', 46),
       (152, 'SG', '新加坡', 'Singapore', 65),
       (153, 'SH', '圣赫勒拿', 'Saint Helena', 290),
       (154, 'SI', '斯洛文尼亚', 'Slovenia', 386),
       (155,
        'SJ',
        '斯瓦尔巴群岛和扬马延岛',
        'Svalbard and Jan Mayen',
        47),
       (156, 'SK', '斯洛伐克', 'Slovakia', 421),
       (157, 'SL', '塞拉利昂', 'Sierra Leone', 232),
       (158, 'SM', '圣马力诺', 'San Marino', 378),
       (159, 'SN', '塞内加尔', 'Senegal', 221),
       (160, 'SO', '索马里', 'Somalia', 252),
       (161, 'SR', '苏里南', 'Suriname', 597),
       (162, 'SS', '南苏丹', 'South Sudan', 211),
       (163, 'ST', '圣多美和普林西比', 'Sao Tome and Principe', 239),
       (164, 'SV', '萨尔瓦多', 'El Salvador', 503),
       (165, 'SX', '荷属圣马丁', 'Sint Maarten', 721),
       (166, 'SY', '叙利亚', 'Syria', 963),
       (167, 'SZ', '斯威士兰', 'Eswatini', 268),
       (168,
        'TC',
        '特克斯和凯科斯群岛',
        'Turks and Caicos Islands',
        649),
       (169, 'TD', '乍得', 'Chad', 235),
       (170,
        'TF',
        '法属南部领土',
        'French Southern Territories',
        262),
       (171, 'TG', '多哥', 'Togo', 228),
       (172, 'TH', '泰国', 'Thailand', 66),
       (173, 'TJ', '塔吉克斯坦', 'Tajikistan', 992),
       (174, 'TK', '托克劳', 'Tokelau', 690),
       (175, 'TL', '东帝汶', 'Timor-Leste', 670),
       (176, 'TM', '土库曼斯坦', 'Turkmenistan', 993),
       (177, 'TN', '突尼斯', 'Tunisia', 216),
       (178, 'TO', '汤加', 'Tonga', 676),
       (179, 'TR', '土耳其', 'Turkey', 90),
       (180, 'TT', '特立尼达和多巴哥', 'Trinidad and Tobago', 1868),
       (181, 'TV', '图瓦卢', 'Tuvalu', 688),
       (182, 'TZ', '坦桑尼亚', 'Tanzania', 255),
       (183, 'UA', '乌克兰', 'Ukraine', 380),
       (184, 'UG', '乌干达', 'Uganda', 256),
       (185, 'US', '美国', 'United States', 1),
       (186, 'UY', '乌拉圭', 'Uruguay', 598),
       (187, 'UZ', '乌兹别克斯坦', 'Uzbekistan', 998),
       (188, 'VA', '梵蒂冈', 'Vatican City', 379),
       (189,
        'VC',
        '圣文森特和格林纳丁斯',
        'Saint Vincent and the Grenadines',
        1784),
       (190, 'VE', '委内瑞拉', 'Venezuela', 58),
       (191, 'VN', '越南', 'Vietnam', 84),
       (192, 'VU', '瓦努阿图', 'Vanuatu', 678),
       (193, 'WS', '萨摩亚', 'Samoa', 685),
       (194, 'YE', '也门', 'Yemen', 967),
       (195, 'ZA', '南非', 'South Africa', 27),
       (196, 'ZM', '赞比亚', 'Zambia', 260),
       (197, 'ZW', '津巴布韦', 'Zimbabwe', 263);

-- 标签表
CREATE TABLE interests
(
    tag_id     bigint PRIMARY KEY AUTO_INCREMENT,
    tag_name   VARCHAR(50) NOT NULL,
    created_at datetime DEFAULT CURRENT_TIMESTAMP,
    updated_at datetime DEFAULT CURRENT_TIMESTAMP,
    deleted_at datetime DEFAULT CURRENT_TIMESTAMP
);

-- 标签翻译表
CREATE TABLE interests_translations
(
    translation_id  bigint PRIMARY KEY AUTO_INCREMENT,
    tag_id          bigint,
    language_code   VARCHAR(5),
    translated_name VARCHAR(50),
    FOREIGN KEY (tag_id) REFERENCES interests (id),
    created_at      datetime DEFAULT CURRENT_TIMESTAMP,
    updated_at      datetime DEFAULT CURRENT_TIMESTAMP,
    deleted_at      datetime DEFAULT CURRENT_TIMESTAMP
);

-- 用户与标签关系表
CREATE TABLE user_interests
(
    user_id    BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    PRIMARY KEY (user_id, tag_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (tag_id) REFERENCES interests (id),
    created_at datetime DEFAULT CURRENT_TIMESTAMP,
    updated_at datetime DEFAULT CURRENT_TIMESTAMP,
    deleted_at datetime DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO interests (tag_name, created_at, updated_at)
VALUES ('Music', NOW(), NOW()),
       ('Sports', NOW(), NOW()),
       ('Travel', NOW(), NOW()),
       ('Technology', NOW(), NOW()),
       ('Cooking', NOW(), NOW()),
       ('Photography', NOW(), NOW()),
       ('Reading', NOW(), NOW()),
       ('Gaming', NOW(), NOW()),
       ('Fitness', NOW(), NOW()),
       ('Movies', NOW(), NOW()),
       ('Art', NOW(), NOW()),
       ('Science', NOW(), NOW()),
       ('History', NOW(), NOW()),
       ('Fashion', NOW(), NOW()),
       ('DIY', NOW(), NOW()),
       ('Nature', NOW(), NOW()),
       ('Adventure', NOW(), NOW()),
       ('Finance', NOW(), NOW()),
       ('Programming', NOW(), NOW()),
       ('Gardening', NOW(), NOW());


INSERT INTO interests_translations (tag_id, language_code, translated_name, created_at, updated_at)
VALUES (1, 'ar', 'موسيقى', NOW(), NOW()),
       (1, 'zh-CN', '音乐', NOW(), NOW()),
       (1, 'zh-TW', '音樂', NOW(), NOW()),
       (1, 'nl', 'Muziek', NOW(), NOW()),
       (1, 'en', 'Music', NOW(), NOW()),
       (1, 'fr', 'Musique', NOW(), NOW()),
       (1, 'de', 'Musik', NOW(), NOW()),
       (1, 'it', 'Musica', NOW(), NOW()),
       (1, 'pt', 'Música', NOW(), NOW()),
       (1, 'es', 'Música', NOW(), NOW()),
       (1, 'bn', 'সঙ্গীত', NOW(), NOW()),
       (1, 'hr', 'Glazba', NOW(), NOW()),
       (1, 'cs', 'Hudba', NOW(), NOW()),
       (1, 'da', 'Musik', NOW(), NOW()),
       (1, 'el', 'Μουσική', NOW(), NOW()),
       (1, 'he', 'מוזיקה', NOW(), NOW()),
       (1, 'hi', 'संगीत', NOW(), NOW()),
       (1, 'hu', 'Zene', NOW(), NOW()),
       (1, 'id', 'Musik', NOW(), NOW()),
       (1, 'ja', '音楽', NOW(), NOW()),
       (1, 'ko', '음악', NOW(), NOW()),
       (1, 'lv', 'Mūzika', NOW(), NOW()),
       (1, 'lt', 'Muzika', NOW(), NOW()),
       (1, 'pl', 'Muzyka', NOW(), NOW()),
       (1, 'ro', 'Muzică', NOW(), NOW()),
       (1, 'sr', 'Музика', NOW(), NOW()),
       (1, 'sk', 'Hudba', NOW(), NOW()),
       (1, 'sl', 'Glasba', NOW(), NOW()),
       (1, 'sv', 'Musik', NOW(), NOW()),
       (1, 'tl', 'Musika', NOW(), NOW()),
       (1, 'tr', 'Müzik', NOW(), NOW()),
       (1, 'uk', 'Музика', NOW(), NOW()),
       (1, 'vi', 'Âm nhạc', NOW(), NOW());


INSERT INTO interests_translations (tag_id, language_code, translated_name, created_at, updated_at)
VALUES (2, 'ar', 'رياضة', NOW(), NOW()),
       (2, 'zh-CN', '体育', NOW(), NOW()),
       (2, 'zh-TW', '體育', NOW(), NOW()),
       (2, 'nl', 'Sport', NOW(), NOW()),
       (2, 'en', 'Sports', NOW(), NOW()),
       (2, 'fr', 'Sports', NOW(), NOW()),
       (2, 'de', 'Sport', NOW(), NOW()),
       (2, 'it', 'Sport', NOW(), NOW()),
       (2, 'pt', 'Esporte', NOW(), NOW()),
       (2, 'es', 'Deportes', NOW(), NOW()),
       (2, 'bn', 'খেলা', NOW(), NOW()),
       (2, 'hr', 'Igre', NOW(), NOW()),
       (2, 'cs', 'Sport', NOW(), NOW()),
       (2, 'da', 'Sport', NOW(), NOW()),
       (2, 'el', 'Αθλητισμός', NOW(), NOW()),
       (2, 'he', 'ספורט', NOW(), NOW()),
       (2, 'hi', 'खेल', NOW(), NOW()),
       (2, 'hu', 'Sport', NOW(), NOW()),
       (2, 'id', 'Olahraga', NOW(), NOW()),
       (2, 'ja', 'スポーツ', NOW(), NOW()),
       (2, 'ko', '스포츠', NOW(), NOW()),
       (2, 'lv', 'Sports', NOW(), NOW()),
       (2, 'lt', 'Sportas', NOW(), NOW()),
       (2, 'pl', 'Sport', NOW(), NOW()),
       (2, 'ro', 'Sport', NOW(), NOW()),
       (2, 'sr', 'Спорт', NOW(), NOW()),
       (2, 'sk', 'Šport', NOW(), NOW()),
       (2, 'sl', 'Šport', NOW(), NOW()),
       (2, 'sv', 'Sport', NOW(), NOW()),
       (2, 'tl', 'Isports', NOW(), NOW()),
       (2, 'tr', 'Spor', NOW(), NOW()),
       (2, 'uk', 'Спорт', NOW(), NOW()),
       (2, 'vi', 'Thể thao', NOW(), NOW()),

       (3, 'ar', 'سفر', NOW(), NOW()),
       (3, 'zh-CN', '旅行', NOW(), NOW()),
       (3, 'zh-TW', '旅遊', NOW(), NOW()),
       (3, 'nl', 'Reizen', NOW(), NOW()),
       (3, 'en', 'Travel', NOW(), NOW()),
       (3, 'fr', 'Voyage', NOW(), NOW()),
       (3, 'de', 'Reisen', NOW(), NOW()),
       (3, 'it', 'Viaggio', NOW(), NOW()),
       (3, 'pt', 'Viagem', NOW(), NOW()),
       (3, 'es', 'Viaje', NOW(), NOW()),
       (3, 'bn', 'ভ্রমণ', NOW(), NOW()),
       (3, 'hr', 'Putovanje', NOW(), NOW()),
       (3, 'cs', 'Cestování', NOW(), NOW()),
       (3, 'da', 'Rejse', NOW(), NOW()),
       (3, 'el', 'Ταξίδι', NOW(), NOW()),
       (3, 'he', 'נסיעה', NOW(), NOW()),
       (3, 'hi', 'यात्रा', NOW(), NOW()),
       (3, 'hu', 'Utazás', NOW(), NOW()),
       (3, 'id', 'Perjalanan', NOW(), NOW()),
       (3, 'ja', '旅行', NOW(), NOW()),
       (3, 'ko', '여행', NOW(), NOW()),
       (3, 'lv', 'Ceļojums', NOW(), NOW()),
       (3, 'lt', 'Kelionė', NOW(), NOW()),
       (3, 'pl', 'Podróż', NOW(), NOW()),
       (3, 'ro', 'Călătorie', NOW(), NOW()),
       (3, 'sr', 'Putovanje', NOW(), NOW()),
       (3, 'sk', 'Cestovanie', NOW(), NOW()),
       (3, 'sl', 'Potovanje', NOW(), NOW()),
       (3, 'sv', 'Resa', NOW(), NOW()),
       (3, 'tl', 'Paglalakbay', NOW(), NOW()),
       (3, 'tr', 'Seyahat', NOW(), NOW()),
       (3, 'uk', 'Подорож', NOW(), NOW()),
       (3, 'vi', 'Du lịch', NOW(), NOW()),

       (4, 'ar', 'تكنولوجيا', NOW(), NOW()),
       (4, 'zh-CN', '技术', NOW(), NOW()),
       (4, 'zh-TW', '科技', NOW(), NOW()),
       (4, 'nl', 'Technologie', NOW(), NOW()),
       (4, 'en', 'Technology', NOW(), NOW()),
       (4, 'fr', 'Technologie', NOW(), NOW()),
       (4, 'de', 'Technologie', NOW(), NOW()),
       (4, 'it', 'Tecnologia', NOW(), NOW()),
       (4, 'pt', 'Tecnologia', NOW(), NOW()),
       (4, 'es', 'Tecnología', NOW(), NOW()),
       (4, 'bn', 'প্রযুক্তি', NOW(), NOW()),
       (4, 'hr', 'Tehnologija', NOW(), NOW()),
       (4, 'cs', 'Technologie', NOW(), NOW()),
       (4, 'da', 'Teknologi', NOW(), NOW()),
       (4, 'el', 'Τεχνολογία', NOW(), NOW()),
       (4, 'he', 'טכנולוגיה', NOW(), NOW()),
       (4, 'hi', 'प्रौद्योगिकी', NOW(), NOW()),
       (4, 'hu', 'Technológia', NOW(), NOW()),
       (4, 'id', 'Teknologi', NOW(), NOW()),
       (4, 'ja', '技術', NOW(), NOW()),
       (4, 'ko', '기술', NOW(), NOW()),
       (4, 'lv', 'Tehnoloģija', NOW(), NOW()),
       (4, 'lt', 'Technologija', NOW(), NOW()),
       (4, 'pl', 'Technologia', NOW(), NOW()),
       (4, 'ro', 'Tehnologie', NOW(), NOW()),
       (4, 'sr', 'Tehnologija', NOW(), NOW()),
       (4, 'sk', 'Technológia', NOW(), NOW()),
       (4, 'sl', 'Tehnologija', NOW(), NOW()),
       (4, 'sv', 'Teknologi', NOW(), NOW()),
       (4, 'tl', 'Teknolohiya', NOW(), NOW()),
       (4, 'tr', 'Teknoloji', NOW(), NOW()),
       (4, 'uk', 'Технологія', NOW(), NOW()),
       (4, 'vi', 'Công nghệ', NOW(), NOW()),

       (5, 'ar', 'طهي', NOW(), NOW()),
       (5, 'zh-CN', '烹饪', NOW(), NOW()),
       (5, 'zh-TW', '烹飪', NOW(), NOW()),
       (5, 'nl', 'Koken', NOW(), NOW()),
       (5, 'en', 'Cooking', NOW(), NOW()),
       (5, 'fr', 'Cuisine', NOW(), NOW()),
       (5, 'de', 'Kochen', NOW(), NOW()),
       (5, 'it', 'Cucina', NOW(), NOW()),
       (5, 'pt', 'Cozinha', NOW(), NOW()),
       (5, 'es', 'Cocina', NOW(), NOW()),
       (5, 'bn', 'রাঁধুনি', NOW(), NOW()),
       (5, 'hr', 'Kuhanje', NOW(), NOW()),
       (5, 'cs', 'Vaření', NOW(), NOW()),
       (5, 'da', 'Madlavning', NOW(), NOW()),
       (5, 'el', 'Μαγειρική', NOW(), NOW()),
       (5, 'he', 'בישול', NOW(), NOW()),
       (5, 'hi', 'पाक', NOW(), NOW()),
       (5, 'hu', 'Főzés', NOW(), NOW()),
       (5, 'id', 'Memasak', NOW(), NOW()),
       (5, 'ja', '料理', NOW(), NOW()),
       (5, 'ko', '요리', NOW(), NOW()),
       (5, 'lv', 'Gatavošana', NOW(), NOW()),
       (5, 'lt', 'Virimas', NOW(), NOW()),
       (5, 'pl', 'Gotowanie', NOW(), NOW()),
       (5, 'ro', 'Gătit', NOW(), NOW()),
       (5, 'sr', 'Kuvanje', NOW(), NOW()),
       (5, 'sk', 'Varenie', NOW(), NOW()),
       (5, 'sl', 'Kuhanje', NOW(), NOW()),
       (5, 'sv', 'Matlagning', NOW(), NOW()),
       (5, 'tl', 'Pagluluto', NOW(), NOW()),
       (5, 'tr', 'Pişirme', NOW(), NOW()),
       (5, 'uk', 'Приготування', NOW(), NOW()),
       (5, 'vi', 'Nấu ăn', NOW(), NOW()),

       (6, 'ar', 'ت fotografía', NOW(), NOW()),
       (6, 'zh-CN', '摄影', NOW(), NOW()),
       (6, 'zh-TW', '攝影', NOW(), NOW()),
       (6, 'nl', 'Fotografie', NOW(), NOW()),
       (6, 'en', 'Photography', NOW(), NOW()),
       (6, 'fr', 'Photographie', NOW(), NOW()),
       (6, 'de', 'Fotografie', NOW(), NOW()),
       (6, 'it', 'Fotografia', NOW(), NOW()),
       (6, 'pt', 'Fotografia', NOW(), NOW()),
       (6, 'es', 'Fotografía', NOW(), NOW()),
       (6, 'bn', 'ছবি তোলা', NOW(), NOW()),
       (6, 'hr', 'Fotografija', NOW(), NOW()),
       (6, 'cs', 'Fotografie', NOW(), NOW()),
       (6, 'da', 'Fotografi', NOW(), NOW()),
       (6, 'el', 'Φωτογραφία', NOW(), NOW()),
       (6, 'he', 'צילום', NOW(), NOW()),
       (6, 'hi', 'फोटोग्राफी', NOW(), NOW()),
       (6, 'hu', 'Fotózás', NOW(), NOW()),
       (6, 'id', 'Fotografi', NOW(), NOW()),
       (6, 'ja', '写真', NOW(), NOW()),
       (6, 'ko', '사진', NOW(), NOW()),
       (6, 'lv', 'Fotogrāfija', NOW(), NOW()),
       (6, 'lt', 'Fotografija', NOW(), NOW()),
       (6, 'pl', 'Fotografia', NOW(), NOW()),
       (6, 'ro', 'Fotografie', NOW(), NOW()),
       (6, 'sr', 'Fotografija', NOW(), NOW()),
       (6, 'sk', 'Fotografia', NOW(), NOW()),
       (6, 'sl', 'Fotografija', NOW(), NOW()),
       (6, 'sv', 'Fotografi', NOW(), NOW()),
       (6, 'tl', 'Potograpiya', NOW(), NOW()),
       (6, 'tr', 'Fotoğrafçılık', NOW(), NOW()),
       (6, 'uk', 'Фотографія', NOW(), NOW()),
       (6, 'vi', 'Nhiếp ảnh', NOW(), NOW()),

       (7, 'ar', 'قراءة', NOW(), NOW()),
       (7, 'zh-CN', '阅读', NOW(), NOW()),
       (7, 'zh-TW', '閱讀', NOW(), NOW()),
       (7, 'nl', 'Lezen', NOW(), NOW()),
       (7, 'en', 'Reading', NOW(), NOW()),
       (7, 'fr', 'Lecture', NOW(), NOW()),
       (7, 'de', 'Lesen', NOW(), NOW()),
       (7, 'it', 'Lettura', NOW(), NOW()),
       (7, 'pt', 'Leitura', NOW(), NOW()),
       (7, 'es', 'Lectura', NOW(), NOW()),
       (7, 'bn', 'পড়া', NOW(), NOW()),
       (7, 'hr', 'Čitanje', NOW(), NOW()),
       (7, 'cs', 'Čtení', NOW(), NOW()),
       (7, 'da', 'Læse', NOW(), NOW()),
       (7, 'el', 'Ανάγνωση', NOW(), NOW()),
       (7, 'he', 'קריאה', NOW(), NOW()),
       (7, 'hi', 'पढ़ाई', NOW(), NOW()),
       (7, 'hu', 'Olvasás', NOW(), NOW()),
       (7, 'id', 'Membaca', NOW(), NOW()),
       (7, 'ja', '読書', NOW(), NOW()),
       (7, 'ko', '독서', NOW(), NOW()),
       (7, 'lv', 'Lasīšana', NOW(), NOW()),
       (7, 'lt', 'Skaitymas', NOW(), NOW()),
       (7, 'pl', 'Czytanie', NOW(), NOW()),
       (7, 'ro', 'Citire', NOW(), NOW()),
       (7, 'sr', 'Čitanje', NOW(), NOW()),
       (7, 'sk', 'Čítanie', NOW(), NOW()),
       (7, 'sl', 'Branje', NOW(), NOW()),
       (7, 'sv', 'Läsning', NOW(), NOW()),
       (7, 'tl', 'Pagbasa', NOW(), NOW()),
       (7, 'tr', 'Okuma', NOW(), NOW()),
       (7, 'uk', 'Читання', NOW(), NOW()),
       (7, 'vi', 'Đọc sách', NOW(), NOW()),

       (8, 'ar', 'ألعاب', NOW(), NOW()),
       (8, 'zh-CN', '游戏', NOW(), NOW()),
       (8, 'zh-TW', '遊戲', NOW(), NOW()),
       (8, 'nl', 'Spel', NOW(), NOW()),
       (8, 'en', 'Gaming', NOW(), NOW()),
       (8, 'fr', 'Jeux', NOW(), NOW()),
       (8, 'de', 'Spielen', NOW(), NOW()),
       (8, 'it', 'Giochi', NOW(), NOW()),
       (8, 'pt', 'Jogos', NOW(), NOW()),
       (8, 'es', 'Juegos', NOW(), NOW()),
       (8, 'bn', 'গেমস', NOW(), NOW()),
       (8, 'hr', 'Igre', NOW(), NOW()),
       (8, 'cs', 'Hraní', NOW(), NOW()),
       (8, 'da', 'Spil', NOW(), NOW()),
       (8, 'el', 'Παιχνίδια', NOW(), NOW()),
       (8, 'he', 'משחקים', NOW(), NOW()),
       (8, 'hi', 'खेलना', NOW(), NOW()),
       (8, 'hu', 'Játékok', NOW(), NOW()),
       (8, 'id', 'Bermain', NOW(), NOW()),
       (8, 'ja', 'ゲーム', NOW(), NOW()),
       (8, 'ko', '게임', NOW(), NOW()),
       (8, 'lv', 'Spēles', NOW(), NOW()),
       (8, 'lt', 'Žaidimai', NOW(), NOW()),
       (8, 'pl', 'Gry', NOW(), NOW()),
       (8, 'ro', 'Jocuri', NOW(), NOW()),
       (8, 'sr', 'Igre', NOW(), NOW()),
       (8, 'sk', 'Hry', NOW(), NOW()),
       (8, 'sl', 'Igre', NOW(), NOW()),
       (8, 'sv', 'Spel', NOW(), NOW()),
       (8, 'tl', 'Laro', NOW(), NOW()),
       (8, 'tr', 'Oyun', NOW(), NOW()),
       (8, 'uk', 'Ігри', NOW(), NOW()),
       (8, 'vi', 'Trò chơi', NOW(), NOW()),

       (9, 'ar', 'لياقة', NOW(), NOW()),
       (9, 'zh-CN', '健身', NOW(), NOW()),
       (9, 'zh-TW', '健身', NOW(), NOW()),
       (9, 'nl', 'Fitness', NOW(), NOW()),
       (9, 'en', 'Fitness', NOW(), NOW()),
       (9, 'fr', 'Fitness', NOW(), NOW()),
       (9, 'de', 'Fitness', NOW(), NOW()),
       (9, 'it', 'Fitness', NOW(), NOW()),
       (9, 'pt', 'Fitness', NOW(), NOW()),
       (9, 'es', 'Fitness', NOW(), NOW()),
       (9, 'bn', 'ফিটনেস', NOW(), NOW()),
       (9, 'hr', 'Fitness', NOW(), NOW()),
       (9, 'cs', 'Fitness', NOW(), NOW()),
       (9, 'da', 'Fitness', NOW(), NOW()),
       (9, 'el', 'Φυτήνινο', NOW(), NOW()),
       (9, 'he', 'כושר', NOW(), NOW()),
       (9, 'hi', 'फिटनेस', NOW(), NOW()),
       (9, 'hu', 'Fitnesz', NOW(), NOW()),
       (9, 'id', 'Kebugaran', NOW(), NOW()),
       (9, 'ja', 'フィットネス', NOW(), NOW()),
       (9, 'ko', '피트니스', NOW(), NOW()),
       (9, 'lv', 'Fitness', NOW(), NOW()),
       (9, 'lt', 'Fitnesas', NOW(), NOW()),
       (9, 'pl', 'Fitness', NOW(), NOW()),
       (9, 'ro', 'Fitness', NOW(), NOW()),
       (9, 'sr', 'Fitness', NOW(), NOW()),
       (9, 'sk', 'Fitness', NOW(), NOW()),
       (9, 'sl', 'Fitness', NOW(), NOW()),
       (9, 'sv', 'Fitness', NOW(), NOW()),
       (9, 'tl', 'Fitness', NOW(), NOW()),
       (9, 'tr', 'Spor', NOW(), NOW()),
       (9, 'uk', 'Фітнес', NOW(), NOW()),
       (9, 'vi', 'Thể hình', NOW(), NOW()),

       (10, 'ar', 'أفلام', NOW(), NOW()),
       (10, 'zh-CN', '电影', NOW(), NOW()),
       (10, 'zh-TW', '電影', NOW(), NOW()),
       (10, 'nl', 'Films', NOW(), NOW()),
       (10, 'en', 'Movies', NOW(), NOW()),
       (10, 'fr', 'Films', NOW(), NOW()),
       (10, 'de', 'Filme', NOW(), NOW()),
       (10, 'it', 'Film', NOW(), NOW()),
       (10, 'pt', 'Filmes', NOW(), NOW()),
       (10, 'es', 'Películas', NOW(), NOW()),
       (10, 'bn', 'চলচ্চিত্র', NOW(), NOW()),
       (10, 'hr', 'Filmovi', NOW(), NOW()),
       (10, 'cs', 'Filmy', NOW(), NOW()),
       (10, 'da', 'Film', NOW(), NOW()),
       (10, 'el', 'Ταινίες', NOW(), NOW()),
       (10, 'he', 'סרטים', NOW(), NOW()),
       (10, 'hi', 'फिल्में', NOW(), NOW()),
       (10, 'hu', 'Filmek', NOW(), NOW()),
       (10, 'id', 'Film', NOW(), NOW()),
       (10, 'ja', '映画', NOW(), NOW()),
       (10, 'ko', '영화', NOW(), NOW()),
       (10, 'lv', 'Filmas', NOW(), NOW()),
       (10, 'lt', 'Filmai', NOW(), NOW()),
       (10, 'pl', 'Filmy', NOW(), NOW()),
       (10, 'ro', 'Filme', NOW(), NOW()),
       (10, 'sr', 'Filmovi', NOW(), NOW()),
       (10, 'sk', 'Filmy', NOW(), NOW()),
       (10, 'sl', 'Filmi', NOW(), NOW()),
       (10, 'sv', 'Filmer', NOW(), NOW()),
       (10, 'tl', 'Mga Pelikula', NOW(), NOW()),
       (10, 'tr', 'Filmler', NOW(), NOW()),
       (10, 'uk', 'Фільми', NOW(), NOW()),
       (10, 'vi', 'Phim', NOW(), NOW()),

       (11, 'ar', 'فنون', NOW(), NOW()),
       (11, 'zh-CN', '艺术', NOW(), NOW()),
       (11, 'zh-TW', '藝術', NOW(), NOW()),
       (11, 'nl', 'Kunst', NOW(), NOW()),
       (11, 'en', 'Art', NOW(), NOW()),
       (11, 'fr', 'Art', NOW(), NOW()),
       (11, 'de', 'Kunst', NOW(), NOW()),
       (11, 'it', 'Arte', NOW(), NOW()),
       (11, 'pt', 'Arte', NOW(), NOW()),
       (11, 'es', 'Arte', NOW(), NOW()),
       (11, 'bn', 'শিল্প', NOW(), NOW()),
       (11, 'hr', 'Umjetnost', NOW(), NOW()),
       (11, 'cs', 'Umění', NOW(), NOW()),
       (11, 'da', 'Kunst', NOW(), NOW()),
       (11, 'el', 'Τέχνη', NOW(), NOW()),
       (11, 'he', 'אמנות', NOW(), NOW()),
       (11, 'hi', 'कला', NOW(), NOW()),
       (11, 'hu', 'Művészet', NOW(), NOW()),
       (11, 'id', 'Seni', NOW(), NOW()),
       (11, 'ja', 'アート', NOW(), NOW()),
       (11, 'ko', '예술', NOW(), NOW()),
       (11, 'lv', 'Māksla', NOW(), NOW()),
       (11, 'lt', 'Menas', NOW(), NOW()),
       (11, 'pl', 'Sztuka', NOW(), NOW()),
       (11, 'ro', 'Artă', NOW(), NOW()),
       (11, 'sr', 'Umetnost', NOW(), NOW()),
       (11, 'sk', 'Umenie', NOW(), NOW()),
       (11, 'sl', 'Umetnost', NOW(), NOW()),
       (11, 'sv', 'Konst', NOW(), NOW()),
       (11, 'tl', 'Sining', NOW(), NOW()),
       (11, 'tr', 'Sanat', NOW(), NOW()),
       (11, 'uk', 'Мистецтво', NOW(), NOW()),
       (11, 'vi', 'Nghệ thuật', NOW(), NOW()),

       (12, 'ar', 'علم', NOW(), NOW()),
       (12, 'zh-CN', '科学', NOW(), NOW()),
       (12, 'zh-TW', '科學', NOW(), NOW()),
       (12, 'nl', 'Wetenschap', NOW(), NOW()),
       (12, 'en', 'Science', NOW(), NOW()),
       (12, 'fr', 'Science', NOW(), NOW()),
       (12, 'de', 'Wissenschaft', NOW(), NOW()),
       (12, 'it', 'Scienza', NOW(), NOW()),
       (12, 'pt', 'Ciência', NOW(), NOW()),
       (12, 'es', 'Ciencia', NOW(), NOW()),
       (12, 'bn', 'বিজ্ঞান', NOW(), NOW()),
       (12, 'hr', 'Znanost', NOW(), NOW()),
       (12, 'cs', 'Věda', NOW(), NOW()),
       (12, 'da', 'Videnskab', NOW(), NOW()),
       (12, 'el', 'Επιστήμη', NOW(), NOW()),
       (12, 'he', 'מדע', NOW(), NOW()),
       (12, 'hi', 'विज्ञान', NOW(), NOW()),
       (12, 'hu', 'Tudomány', NOW(), NOW()),
       (12, 'id', 'Ilmu', NOW(), NOW()),
       (12, 'ja', '科学', NOW(), NOW()),
       (12, 'ko', '과학', NOW(), NOW()),
       (12, 'lv', 'Zinātne', NOW(), NOW()),
       (12, 'lt', 'Mokslas', NOW(), NOW()),
       (12, 'pl', 'Nauka', NOW(), NOW()),
       (12, 'ro', 'Știință', NOW(), NOW()),
       (12, 'sr', 'Nauka', NOW(), NOW()),
       (12, 'sk', 'Veda', NOW(), NOW()),
       (12, 'sl', 'Znanost', NOW(), NOW()),
       (12, 'sv', 'Vetenskap', NOW(), NOW()),
       (12, 'tl', 'Agham', NOW(), NOW()),
       (12, 'tr', 'Bilim', NOW(), NOW()),
       (12, 'uk', 'Наука', NOW(), NOW()),
       (12, 'vi', 'Khoa học', NOW(), NOW()),

       (13, 'ar', 'تاريخ', NOW(), NOW()),
       (13, 'zh-CN', '历史', NOW(), NOW()),
       (13, 'zh-TW', '歷史', NOW(), NOW()),
       (13, 'nl', 'Geschiedenis', NOW(), NOW()),
       (13, 'en', 'History', NOW(), NOW()),
       (13, 'fr', 'Histoire', NOW(), NOW()),
       (13, 'de', 'Geschichte', NOW(), NOW()),
       (13, 'it', 'Storia', NOW(), NOW()),
       (13, 'pt', 'História', NOW(), NOW()),
       (13, 'es', 'Historia', NOW(), NOW()),
       (13, 'bn', 'ইতিহাস', NOW(), NOW()),
       (13, 'hr', 'Povijest', NOW(), NOW()),
       (13, 'cs', 'Dějiny', NOW(), NOW()),
       (13, 'da', 'Historie', NOW(), NOW()),
       (13, 'el', 'Ιστορία', NOW(), NOW()),
       (13, 'he', 'היסטוריה', NOW(), NOW()),
       (13, 'hi', 'इतिहास', NOW(), NOW()),
       (13, 'hu', 'Történe', NOW(), NOW()),
       (13, 'id', 'Sejarah', NOW(), NOW()),
       (13, 'ja', '歴史', NOW(), NOW()),
       (13, 'ko', '역사', NOW(), NOW()),
       (13, 'lv', 'Vēsture', NOW(), NOW()),
       (13, 'lt', 'Istorija', NOW(), NOW()),
       (13, 'pl', 'Historia', NOW(), NOW()),
       (13, 'ro', 'Istorie', NOW(), NOW()),
       (13, 'sr', 'Istorija', NOW(), NOW()),
       (13, 'sk', 'História', NOW(), NOW()),
       (13, 'sl', 'Zgodovina', NOW(), NOW()),
       (13, 'sv', 'Historia', NOW(), NOW()),
       (13, 'tl', 'Kasaysayan', NOW(), NOW()),
       (13, 'tr', 'Tarih', NOW(), NOW()),
       (13, 'uk', 'Історія', NOW(), NOW()),
       (13, 'vi', 'Lịch sử', NOW(), NOW()),

       (14, 'ar', 'موضة', NOW(), NOW()),
       (14, 'zh-CN', '时尚', NOW(), NOW()),
       (14, 'zh-TW', '時尚', NOW(), NOW()),
       (14, 'nl', 'Mode', NOW(), NOW()),
       (14, 'en', 'Fashion', NOW(), NOW()),
       (14, 'fr', 'Mode', NOW(), NOW()),
       (14, 'de', 'Mode', NOW(), NOW()),
       (14, 'it', 'Moda', NOW(), NOW()),
       (14, 'pt', 'Moda', NOW(), NOW()),
       (14, 'es', 'Moda', NOW(), NOW()),
       (14, 'bn', 'ফ্যাশন', NOW(), NOW()),
       (14, 'hr', 'Modna', NOW(), NOW()),
       (14, 'cs', 'Móda', NOW(), NOW()),
       (14, 'da', 'Mode', NOW(), NOW()),
       (14, 'el', 'Μόδα', NOW(), NOW()),
       (14, 'he', 'אופנה', NOW(), NOW()),
       (14, 'hi', 'फैशन', NOW(), NOW()),
       (14, 'hu', 'Divat', NOW(), NOW()),
       (14, 'id', 'Mode', NOW(), NOW()),
       (14, 'ja', 'ファッション', NOW(), NOW()),
       (14, 'ko', '패션', NOW(), NOW()),
       (14, 'lv', 'Modes', NOW(), NOW()),
       (14, 'lt', 'Mada', NOW(), NOW()),
       (14, 'pl', 'Moda', NOW(), NOW()),
       (14, 'ro', 'Modă', NOW(), NOW()),
       (14, 'sr', 'Moda', NOW(), NOW()),
       (14, 'sk', 'Móda', NOW(), NOW()),
       (14, 'sl', 'Moda', NOW(), NOW()),
       (14, 'sv', 'Mode', NOW(), NOW()),
       (14, 'tl', 'Uso', NOW(), NOW()),
       (14, 'tr', 'Tarz', NOW(), NOW()),
       (14, 'uk', 'Мода', NOW(), NOW()),
       (14, 'vi', 'Thời trang', NOW(), NOW()),

       (15, 'ar', 'اعمال يدوية', NOW(), NOW()),
       (15, 'zh-CN', 'DIY', NOW(), NOW()),
       (15, 'zh-TW', '自己做', NOW(), NOW()),
       (15, 'nl', 'Doe het zelf', NOW(), NOW()),
       (15, 'en', 'DIY', NOW(), NOW()),
       (15, 'fr', 'Bricolage', NOW(), NOW()),
       (15, 'de', 'Selbstgemacht', NOW(), NOW()),
       (15, 'it', 'Fai da te', NOW(), NOW()),
       (15, 'pt', 'Faça você mesmo', NOW(), NOW()),
       (15, 'es', 'Hazlo tú mismo', NOW(), NOW()),
       (15, 'bn', 'নিজে করুন', NOW(), NOW()),
       (15, 'hr', 'Uradi to sam', NOW(), NOW()),
       (15, 'cs', 'Udělej si sám', NOW(), NOW()),
       (15, 'da', 'Gør det selv', NOW(), NOW()),
       (15, 'el', 'Φτιάξτο μόνος σου', NOW(), NOW()),
       (15, 'he', 'עשה זאת בעצמך', NOW(), NOW()),
       (15, 'hi', 'खुद करो', NOW(), NOW()),
       (15, 'hu', 'Készítsd magad', NOW(), NOW()),
       (15, 'id', 'Buat sendiri', NOW(), NOW()),
       (15, 'ja', '自分で作る', NOW(), NOW()),
       (15, 'ko', '직접 만들기', NOW(), NOW()),
       (15, 'lv', 'Izgatavot savu', NOW(), NOW()),
       (15, 'lt', 'Pasidaryk pats', NOW(), NOW()),
       (15, 'pl', 'Zrób to sam', NOW(), NOW()),
       (15, 'ro', 'Fă-o singur', NOW(), NOW()),
       (15, 'sr', 'Uradi to sam', NOW(), NOW()),
       (15, 'sk', 'Urob si sám', NOW(), NOW()),
       (15, 'sl', 'Naredite sami', NOW(), NOW()),
       (15, 'sv', 'Gör det själv', NOW(), NOW()),
       (15, 'tl', 'Gawainin', NOW(), NOW()),
       (15, 'tr', 'Kendin yap', NOW(), NOW()),
       (15, 'uk', 'Зроби сам', NOW(), NOW()),
       (15, 'vi', 'Tự làm', NOW(), NOW()),

       (16, 'ar', 'طبيعة', NOW(), NOW()),
       (16, 'zh-CN', '自然', NOW(), NOW()),
       (16, 'zh-TW', '自然', NOW(), NOW()),
       (16, 'nl', 'Natuur', NOW(), NOW()),
       (16, 'en', 'Nature', NOW(), NOW()),
       (16, 'fr', 'Nature', NOW(), NOW()),
       (16, 'de', 'Natur', NOW(), NOW()),
       (16, 'it', 'Natura', NOW(), NOW()),
       (16, 'pt', 'Natureza', NOW(), NOW()),
       (16, 'es', 'Naturaleza', NOW(), NOW()),
       (16, 'bn', 'প্রকৃতি', NOW(), NOW()),
       (16, 'hr', 'Priroda', NOW(), NOW()),
       (16, 'cs', 'Příroda', NOW(), NOW()),
       (16, 'da', 'Natur', NOW(), NOW()),
       (16, 'el', 'Φύση', NOW(), NOW()),
       (16, 'he', 'טבע', NOW(), NOW()),
       (16, 'hi', 'प्रकृति', NOW(), NOW()),
       (16, 'hu', 'Természet', NOW(), NOW()),
       (16, 'id', 'Alam', NOW(), NOW()),
       (16, 'ja', '自然', NOW(), NOW()),
       (16, 'ko', '자연', NOW(), NOW()),
       (16, 'lv', 'Daba', NOW(), NOW()),
       (16, 'lt', 'Gamtos', NOW(), NOW()),
       (16, 'pl', 'Przyroda', NOW(), NOW()),
       (16, 'ro', 'Natură', NOW(), NOW()),
       (16, 'sr', 'Priroda', NOW(), NOW()),
       (16, 'sk', 'Príroda', NOW(), NOW()),
       (16, 'sl', 'Narava', NOW(), NOW()),
       (16, 'sv', 'Natur', NOW(), NOW()),
       (16, 'tl', 'Kalikasan', NOW(), NOW()),
       (16, 'tr', 'Doğa', NOW(), NOW()),
       (16, 'uk', 'Природа', NOW(), NOW()),
       (16, 'vi', 'Thiên nhiên', NOW(), NOW()),

       (17, 'ar', 'مغامرة', NOW(), NOW()),
       (17, 'zh-CN', '冒险', NOW(), NOW()),
       (17, 'zh-TW', '冒險', NOW(), NOW()),
       (17, 'nl', 'Avontuur', NOW(), NOW()),
       (17, 'en', 'Adventure', NOW(), NOW()),
       (17, 'fr', 'Aventure', NOW(), NOW()),
       (17, 'de', 'Abenteuer', NOW(), NOW()),
       (17, 'it', 'Avventura', NOW(), NOW()),
       (17, 'pt', 'Aventura', NOW(), NOW()),
       (17, 'es', 'Aventura', NOW(), NOW()),
       (17, 'bn', 'অভিযান', NOW(), NOW()),
       (17, 'hr', 'Avantura', NOW(), NOW()),
       (17, 'cs', 'Dobrodružství', NOW(), NOW()),
       (17, 'da', 'Eventyr', NOW(), NOW()),
       (17, 'el', 'Περιπέτεια', NOW(), NOW()),
       (17, 'he', 'הרפתקה', NOW(), NOW()),
       (17, 'hi', 'साहसिक', NOW(), NOW()),
       (17, 'hu', 'Kaland', NOW(), NOW()),
       (17, 'id', 'Petualangan', NOW(), NOW()),
       (17, 'ja', '冒険', NOW(), NOW()),
       (17, 'ko', '모험', NOW(), NOW()),
       (17, 'lv', 'Piedzīvojums', NOW(), NOW()),
       (17, 'lt', 'Nuotykiai', NOW(), NOW()),
       (17, 'pl', 'Przygoda', NOW(), NOW()),
       (17, 'ro', 'Aventura', NOW(), NOW()),
       (17, 'sr', 'Avantura', NOW(), NOW()),
       (17, 'sk', 'Dobrodružstvo', NOW(), NOW()),
       (17, 'sl', 'Avantura', NOW(), NOW()),
       (17, 'sv', 'Äventyr', NOW(), NOW()),
       (17, 'tl', 'Pakikipagsapalaran', NOW(), NOW()),
       (17, 'tr', 'Macerası', NOW(), NOW()),
       (17, 'uk', 'Пригода', NOW(), NOW()),
       (17, 'vi', 'Cuộc phiêu lưu', NOW(), NOW()),

       (18, 'ar', 'تمويل', NOW(), NOW()),
       (18, 'zh-CN', '财务', NOW(), NOW()),
       (18, 'zh-TW', '財務', NOW(), NOW()),
       (18, 'nl', 'Financiën', NOW(), NOW()),
       (18, 'en', 'Finance', NOW(), NOW()),
       (18, 'fr', 'Finance', NOW(), NOW()),
       (18, 'de', 'Finanzen', NOW(), NOW()),
       (18, 'it', 'Finanza', NOW(), NOW()),
       (18, 'pt', 'Finanças', NOW(), NOW()),
       (18, 'es', 'Finanzas', NOW(), NOW()),
       (18, 'bn', 'অর্থায়ন', NOW(), NOW()),
       (18, 'hr', 'Financije', NOW(), NOW()),
       (18, 'cs', 'Finance', NOW(), NOW()),
       (18, 'da', 'Økonomi', NOW(), NOW()),
       (18, 'el', 'Οικονομία', NOW(), NOW()),
       (18, 'he', 'פיננסים', NOW(), NOW()),
       (18, 'hi', 'वित्त', NOW(), NOW()),
       (18, 'hu', 'Pénzügy', NOW(), NOW()),
       (18, 'id', 'Keuangan', NOW(), NOW()),
       (18, 'ja', '財務', NOW(), NOW()),
       (18, 'ko', '재정', NOW(), NOW()),
       (18, 'lv', 'Finanses', NOW(), NOW()),
       (18, 'lt', 'Finansai', NOW(), NOW()),
       (18, 'pl', 'Finanse', NOW(), NOW()),
       (18, 'ro', 'Finanțe', NOW(), NOW()),
       (18, 'sr', 'Finansije', NOW(), NOW()),
       (18, 'sk', 'Financie', NOW(), NOW()),
       (18, 'sl', 'Finance', NOW(), NOW()),
       (18, 'sv', 'Finans', NOW(), NOW()),
       (18, 'tl', 'Pananalapi', NOW(), NOW()),
       (18, 'tr', 'Finans', NOW(), NOW()),
       (18, 'uk', 'Фінанси', NOW(), NOW()),
       (18, 'vi', 'Tài chính', NOW(), NOW()),

       (19, 'ar', 'برمجة', NOW(), NOW()),
       (19, 'zh-CN', '编程', NOW(), NOW()),
       (19, 'zh-TW', '程式', NOW(), NOW()),
       (19, 'nl', 'Programmeren', NOW(), NOW()),
       (19, 'en', 'Programming', NOW(), NOW()),
       (19, 'fr', 'Programmation', NOW(), NOW()),
       (19, 'de', 'Programmierung', NOW(), NOW()),
       (19, 'it', 'Programmazione', NOW(), NOW()),
       (19, 'pt', 'Programação', NOW(), NOW()),
       (19, 'es', 'Programación', NOW(), NOW()),
       (19, 'bn', 'প্রোগ্রামিং', NOW(), NOW()),
       (19, 'hr', 'Programiranje', NOW(), NOW()),
       (19, 'cs', 'Programování', NOW(), NOW()),
       (19, 'da', 'Programmering', NOW(), NOW()),
       (19, 'el', 'Προγραμματισμός', NOW(), NOW()),
       (19, 'he', 'תכנות', NOW(), NOW()),
       (19, 'hi', 'प्रोग्रामिंग', NOW(), NOW()),
       (19, 'hu', 'Programozás', NOW(), NOW()),
       (19, 'id', 'Pemrograman', NOW(), NOW()),
       (19, 'ja', 'プログラミング', NOW(), NOW()),
       (19, 'ko', '프로그래밍', NOW(), NOW()),
       (19, 'lv', 'Programēšana', NOW(), NOW()),
       (19, 'lt', 'Programavimas', NOW(), NOW()),
       (19, 'pl', 'Programowanie', NOW(), NOW()),
       (19, 'ro', 'Programare', NOW(), NOW()),
       (19, 'sr', 'Programiranje', NOW(), NOW()),
       (19, 'sk', 'Programovanie', NOW(), NOW()),
       (19, 'sl', 'Programiranje', NOW(), NOW()),
       (19, 'sv', 'Programmering', NOW(), NOW()),
       (19, 'tl', 'Pagbuo ng programa', NOW(), NOW()),
       (19, 'tr', 'Programlama', NOW(), NOW()),
       (19, 'uk', 'Програмування', NOW(), NOW()),
       (19, 'vi', 'Lập trình', NOW(), NOW()),

       (20, 'ar', 'حديقة', NOW(), NOW()),
       (20, 'zh-CN', '园艺', NOW(), NOW()),
       (20, 'zh-TW', '園藝', NOW(), NOW()),
       (20, 'nl', 'Tuinieren', NOW(), NOW()),
       (20, 'en', 'Gardening', NOW(), NOW()),
       (20, 'fr', 'Jardinage', NOW(), NOW()),
       (20, 'de', 'Gartenarbeit', NOW(), NOW()),
       (20, 'it', 'Giardinaggio', NOW(), NOW()),
       (20, 'pt', 'Jardinagem', NOW(), NOW()),
       (20, 'es', 'Jardinería', NOW(), NOW()),
       (20, 'bn', 'গার্ডেনিং', NOW(), NOW()),
       (20, 'hr', 'Vrtlarstvo', NOW(), NOW()),
       (20, 'cs', 'Zahradničení', NOW(), NOW()),
       (20, 'da', 'Havearbejde', NOW(), NOW()),
       (20, 'el', 'Κηπουρική', NOW(), NOW()),
       (20, 'he', 'גינון', NOW(), NOW()),
       (20, 'hi', 'बागवानी', NOW(), NOW()),
       (20, 'hu', 'Kertészkedés', NOW(), NOW()),
       (20, 'id', 'Berkebun', NOW(), NOW()),
       (20, 'ja', 'ガーデニング', NOW(), NOW()),
       (20, 'ko', '원예', NOW(), NOW()),
       (20, 'lv', 'Dārzs', NOW(), NOW()),
       (20, 'lt', 'Sodas', NOW(), NOW()),
       (20, 'pl', 'Ogrodnictwo', NOW(), NOW()),
       (20, 'ro', 'Grădinărit', NOW(), NOW()),
       (20, 'sr', 'Vrtlarstvo', NOW(), NOW()),
       (20, 'sk', 'Záhradníctvo', NOW(), NOW()),
       (20, 'sl', 'Vrtnarstvo', NOW(), NOW()),
       (20, 'sv', 'Trädgårdsskötsel', NOW(), NOW()),
       (20, 'tl', 'Paghahardin', NOW(), NOW()),
       (20, 'tr', 'Bahçe işleri', NOW(), NOW()),
       (20, 'uk', 'Садівництво', NOW(), NOW()),
       (20, 'vi', 'Làm vườn', NOW(), NOW());